
name: testthat testing

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e 'install.packages("remotes"); remotes::install_deps(dependencies = TRUE, path = "pkg/vswift")'
      - name: Run tests
        run: Rscript -e 'devtools::test()'
