name: test build and check

on:
  push:
    branches: [main, master, test]
  # Run weekly on Monday
  schedule:
    - cron: 0 0 * * 1

jobs:
  test-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        r: [4.2.0, 4.3.0, 4.4.0]
        os: ['macos-latest', 'windows-latest', 'ubuntu-latest']
        
    name: R version ${{ matrix.r }} check on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
        env:
          TINYTEX_INSTALLER: TinyTex
        with:
          r-version: ${{ matrix.r }}
          
      - name: Install Linux libraries
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y libssl-dev libfontconfig1-dev libcurl4-openssl-dev libxml2-dev libharfbuzz-dev
          sudo apt-get install -y libgit2-dev libharfbuzz-dev libfribidi-dev
          sudo apt-get install -y libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
          sudo apt-get install -y gfortran libglpk-dev
        shell: bash

      - name: Install dependencies
        run: Rscript -e 'install.packages("pak"); pak::local_install(dependencies = TRUE)'
        working-directory: pkg/vswift
        
      - name: Build tar & CRAN check for Mac & Ubuntu
        if: ${{ matrix.os  == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: |
          R CMD build .
          R CMD check --as-cran vswift_0.1.0.tar.gz
        shell: bash
        working-directory: pkg/vswift
        
      - name: Build tar & CRAN check for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          R CMD build --no-build-vignettes .
          R CMD check --no-manual --as-cran vswift_0.1.0.tar.gz
        shell: cmd
        working-directory: pkg/vswift
